#ifndef EAGOLD_RECOVERY_V0116_MQH
#define EAGOLD_RECOVERY_V0116_MQH

double RecoveryStepForLevel(int level){double step=RecoveryMinDistance;if(level<0)level=0;if(EnableRecoveryStepMultiplier&&RecoveryStepMultiplier>1.0){for(int i=0;i<level;i++){step*=RecoveryStepMultiplier;if(RecoveryStepMax>0.0&&step>=RecoveryStepMax){step=RecoveryStepMax;break;}}}if(RecoveryStepMax>0.0&&step>RecoveryStepMax)step=RecoveryStepMax;return(step);}
int RecoveryLevel(int direction){int count=CountDirectionPositions(direction);if(count<=1)return(0);return(count-1);}
double R11GrossExposureLots(){return(DirectionLots(OP_BUY)+DirectionLots(OP_SELL));}
double R11NetExposureLots(){return(MathAbs(DirectionLots(OP_BUY)-DirectionLots(OP_SELL)));}
double R11NetToGrossRatio(){double gross=R11GrossExposureLots();if(gross<=0.0)return(1.0);return(R11NetExposureLots()/gross);}
double R11RecoveryLotFactor(){if(!EnableR11ExposureGovernor)return(1.0);double gross=R11GrossExposureLots();double block=R11BlockGrossExposureLots;double taper=R11TaperStartGrossExposureLots;double minRatio=R11MinNetToGrossRatio;if(block>0.0&&gross>=block)return(0.0);if(gross>=taper&&minRatio>0.0&&gross>0.0&&R11NetToGrossRatio()<minRatio)return(0.0);if(block<=taper||block<=0.0||gross<=taper)return(1.0);double minFactor=R11MinRecoveryLotFactor;if(minFactor<0.0)minFactor=0.0;if(minFactor>1.0)minFactor=1.0;double progress=(gross-taper)/(block-taper);if(progress<0.0)progress=0.0;if(progress>1.0)progress=1.0;double factor=1.0-progress*(1.0-minFactor);if(factor<minFactor)factor=minFactor;return(factor);}
bool R11RecoveryAdditionAllowed(double candidateLot,double &adjustedLot){adjustedLot=0.0;if(candidateLot<=0.0)return(false);double gross=R11GrossExposureLots();double block=R11BlockGrossExposureLots;double factor=R11RecoveryLotFactor();if(factor<=0.0)return(false);adjustedLot=NormalizeLot(candidateLot*factor);if(block>0.0){double remainingCapacity=NormalizeDouble(block-gross,DigitsLots);if(remainingCapacity<Lot){adjustedLot=0.0;return(false);}if(adjustedLot>remainingCapacity)adjustedLot=NormalizeLot(remainingCapacity);}if(adjustedLot<Lot)return(false);return(true);}
bool GetLatestActivatedPosition(int direction,double &latestPrice,double &latestLot,int &latestTicket){int type=(direction==OP_BUY?OP_BUY:OP_SELL);latestPrice=0.0;latestLot=NormalizeLot(Lot);latestTicket=-1;datetime latestTime=0;bool found=false;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;datetime t=OrderOpenTime();int ticket=OrderTicket();if(!found||t>latestTime||(t==latestTime&&ticket>latestTicket)){found=true;latestTime=t;latestPrice=OrderOpenPrice();latestLot=OrderLots();latestTicket=ticket;}}return(found);}
bool HasRecoveryPending(int direction){string tag=(direction==OP_BUY?"EAGOLD BUY RECOVERY":"EAGOLD SELL RECOVERY");int type=(direction==OP_BUY?OP_BUYSTOP:OP_SELLSTOP);for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;if(StringFind(OrderComment(),tag,0)>=0)return(true);}return(false);}
double NextRecoveryLot(double previousLot){if(previousLot<=0.0)return(NormalizeLot(Lot));return(NormalizeLot(previousLot*Multiplier+LotIncrement));}
EAGOLD_ActionResult BuyRecovery(){if(SmartGrid1<=0.0||RecoveryMinDistance<=0.0)return(EAGOLD_ACTION_BLOCKED);if(CountDirectionPositions(OP_BUY)<=0||HasRecoveryPending(OP_BUY))return(EAGOLD_ACTION_BLOCKED);double p=0.0,l=Lot;int t=-1;if(!GetLatestActivatedPosition(OP_BUY,p,l,t))return(EAGOLD_ACTION_BLOCKED);RefreshRates();if(p-Ask<PointsToPrice(2.0*SmartGrid1))return(EAGOLD_ACTION_BLOCKED);int level=RecoveryLevel(OP_BUY)-1;double dynamicStep=RecoveryStepForLevel(level);double stop=NormalizePrice(Ask+PointsToPrice(dynamicStep));if(stop<=Ask+MarketInfo(Symbol(),MODE_STOPLEVEL)*Point)return(EAGOLD_ACTION_BLOCKED);double candidateLot=NextRecoveryLot(l),recoveryLot=0.0;if(!R11RecoveryAdditionAllowed(candidateLot,recoveryLot))return(EAGOLD_ACTION_BLOCKED);Print(EA_NAME," RULE 11 BUY STEP: level=",level," step=",DoubleToString(dynamicStep,1)," multiplier=",DoubleToString(RecoveryStepMultiplier,2)," lot=",DoubleToString(recoveryLot,DigitsLots));int recoveryTicket=SendPending(OP_BUYSTOP,stop,recoveryLot,"EAGOLD BUY RECOVERY");if(recoveryTicket>0){CreateEngineActionMarker("R5","RECOVERY",OP_BUY,recoveryLot);CreateEngineActionMarker("R11","STEP "+DoubleToString(dynamicStep,0),OP_BUY,0.0);EAGOLD_ApplyActionResult(EAGOLD_ACTION_COMPLETED,"R11","RECOVERY_ADDITION",OP_BUY,recoveryLot);return(EAGOLD_ACTION_COMPLETED);}return(EAGOLD_ACTION_FAILED);}
EAGOLD_ActionResult SellRecovery(){if(SmartGrid1<=0.0||RecoveryMinDistance<=0.0)return(EAGOLD_ACTION_BLOCKED);if(CountDirectionPositions(OP_SELL)<=0||HasRecoveryPending(OP_SELL))return(EAGOLD_ACTION_BLOCKED);double p=0.0,l=Lot;int t=-1;if(!GetLatestActivatedPosition(OP_SELL,p,l,t))return(EAGOLD_ACTION_BLOCKED);RefreshRates();if(Bid-p<PointsToPrice(2.0*SmartGrid1))return(EAGOLD_ACTION_BLOCKED);int level=RecoveryLevel(OP_SELL)-1;double dynamicStep=RecoveryStepForLevel(level);double stop=NormalizePrice(Bid-PointsToPrice(dynamicStep));if(stop>=Bid-MarketInfo(Symbol(),MODE_STOPLEVEL)*Point)return(EAGOLD_ACTION_BLOCKED);double candidateLot=NextRecoveryLot(l),recoveryLot=0.0;if(!R11RecoveryAdditionAllowed(candidateLot,recoveryLot))return(EAGOLD_ACTION_BLOCKED);Print(EA_NAME," RULE 11 SELL STEP: level=",level," step=",DoubleToString(dynamicStep,1)," multiplier=",DoubleToString(RecoveryStepMultiplier,2)," lot=",DoubleToString(recoveryLot,DigitsLots));int recoveryTicket=SendPending(OP_SELLSTOP,stop,recoveryLot,"EAGOLD SELL RECOVERY");if(recoveryTicket>0){CreateEngineActionMarker("R5","RECOVERY",OP_SELL,recoveryLot);CreateEngineActionMarker("R11","STEP "+DoubleToString(dynamicStep,0),OP_SELL,0.0);EAGOLD_ApplyActionResult(EAGOLD_ACTION_COMPLETED,"R11","RECOVERY_ADDITION",OP_SELL,recoveryLot);return(EAGOLD_ACTION_COMPLETED);}return(EAGOLD_ACTION_FAILED);}
#endif
