#ifndef EAGOLD_ENGINE2_EXPOSURE_MQH
#define EAGOLD_ENGINE2_EXPOSURE_MQH

//==================================================================
// ENGINE 2 — EXPOSURE MANAGEMENT
// Structural consolidation of the v0.106 business modules.
// Behavior intentionally preserved: R9 hedge + R10 reduction.
// No trading logic redesign.
//==================================================================

//==================================================================
// R9 — EXPOSURE HEDGE
// Source responsibility consolidated from EAGOLD_R9.mqh.
//==================================================================

bool IntArrayContains(int &arr[],int ticket){for(int i=0;i<ArraySize(arr);i++)if(arr[i]==ticket)return(true);return(false);}

void IntArrayAdd(int &arr[],int ticket){if(ticket<0||IntArrayContains(arr,ticket))return;int n=ArraySize(arr);ArrayResize(arr,n+1);arr[n]=ticket;}

bool R9Processed(int ticket){return(IntArrayContains(g_r9ProcessedTickets,ticket));}

void R9MarkProcessed(int ticket){IntArrayAdd(g_r9ProcessedTickets,ticket);}

void R9SeedExistingPositions(){for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder())continue;int type=OrderType();if(type==OP_BUY||type==OP_SELL)R9MarkProcessed(OrderTicket());}}

bool R9GetNewExposureState(int &lightDirection,double &exposure,double &lightLots,double &heavyLots){double b=DirectionLots(OP_BUY),s=DirectionLots(OP_SELL);exposure=MathAbs(b-s);lightDirection=-1;lightLots=MathMin(b,s);heavyLots=MathMax(b,s);if(exposure<R9ExposureTriggerLots)return(false);if(b<s)lightDirection=OP_BUY;else if(s<b)lightDirection=OP_SELL;else return(false);return(true);}

bool R9HedgeFromActivatedTicket(int ticket){if(!EnableR9Hedge)return(false);if(!OrderSelect(ticket,SELECT_BY_TICKET,MODE_TRADES))return(false);if(!IsEAGOLDOrder())return(false);int type=OrderType();if(type!=OP_BUY&&type!=OP_SELL)return(false);double triggerLot=OrderLots();int light=-1;double exposure=0.0,lightLots=0.0,heavyLots=0.0;if(!R9GetNewExposureState(light,exposure,lightLots,heavyLots)){g_r9HedgeActive=false;return(false);}int heavy=HeavyDirection();if(type!=heavy)return(false);double hedgeLot=NormalizeLot(triggerLot*R9HedgeFraction);double maxHedge=NormalizeLot(exposure*R9BalanceCap);if(maxHedge<Lot)return(false);if(hedgeLot>maxHedge)hedgeLot=maxHedge;hedgeLot=NormalizeLot(hedgeLot);if(hedgeLot<=0.0)return(false);int hedgeTicket=SendMarket(light,hedgeLot,StringFormat("EAGOLD R9 HEDGE FROM #%d",ticket));if(hedgeTicket>0){R9MarkProcessed(hedgeTicket);g_r9HedgeActive=true;Print(EA_NAME," RULE 9 HEDGE: activation=",ticket," triggerLot=",DoubleToString(triggerLot,DigitsLots)," light=",(light==OP_BUY?"BUY":"SELL")," exposure=",DoubleToString(exposure,DigitsLots)," hedgeLot=",DoubleToString(hedgeLot,DigitsLots)," cap=",DoubleToString(R9BalanceCap,2)," newTicket=",hedgeTicket);CreateEngineActionMarker("R9","HEDGE",light,hedgeLot);return(true);}return(false);}

void Rule9DetectActivatedOrders(){if(!EnableR9Hedge)return;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder())continue;int type=OrderType();if(type!=OP_BUY&&type!=OP_SELL)continue;int ticket=OrderTicket();if(R9Processed(ticket))continue;R9HedgeFromActivatedTicket(ticket);R9MarkProcessed(ticket);}double exposure=ExposureLots();if(exposure<R9ExposureTriggerLots)g_r9HedgeActive=false;}

//==================================================================
// R10 — EXPOSURE REDUCTION
// Source responsibility consolidated from EAGOLD_R10.mqh.
//==================================================================

void CreateR10VisualMarker(int targetDirection,double reducedLots,double realizedMoney,double beforeExposure,double afterExposure,double beforeGross,double afterGross){if(!EnableR10VisualMarker||reducedLots<Lot)return;RefreshRates();double price=NormalizePrice((Bid+Ask)/2.0);string side=(targetDirection==OP_BUY?"BUY":"SELL");color markerColor=(targetDirection==OP_BUY?R10BuyMarkerColor:R10SellMarkerColor);string base=R10_MARKER_PREFIX+IntegerToString(GetTickCount())+"_"+IntegerToString(MathRand());string text=StringFormat("R10 %s %.2f",side,reducedLots);datetime stamp=TimeCurrent();if(ObjectCreate(0,base,OBJ_TEXT,0,stamp,NormalizePrice(price+PointsToPrice(R10MarkerOffsetPoints)))){ObjectSetString(0,base,OBJPROP_TEXT,text);ObjectSetString(0,base,OBJPROP_FONT,R10MarkerFont);ObjectSetInteger(0,base,OBJPROP_FONTSIZE,R10MarkerFontSize);ObjectSetInteger(0,base,OBJPROP_COLOR,markerColor);ObjectSetInteger(0,base,OBJPROP_ANCHOR,ANCHOR_LEFT_UPPER);ObjectSetInteger(0,base,OBJPROP_SELECTABLE,false);ObjectSetInteger(0,base,OBJPROP_SELECTED,false);ObjectSetInteger(0,base,OBJPROP_HIDDEN,false);ObjectSetInteger(0,base,OBJPROP_BACK,false);}Print(EA_NAME," R10 VISUAL MARKER: ",side," reduced=",DoubleToString(reducedLots,DigitsLots)," realized=$",DoubleToString(realizedMoney,2)," exposure=",DoubleToString(beforeExposure,DigitsLots)," -> ",DoubleToString(afterExposure,DigitsLots)," gross=",DoubleToString(beforeGross,DigitsLots)," -> ",DoubleToString(afterGross,DigitsLots));ChartRedraw(0);}

bool ReduceDirectionByLots(int direction,double lotsToReduce,double &realizedMoney){realizedMoney=0.0;if(lotsToReduce<Lot)return(false);int type=(direction==OP_BUY?OP_BUY:OP_SELL);int tickets[];ArrayResize(tickets,0);double ticketLots[];ArrayResize(ticketLots,0);for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;int n=ArraySize(tickets);ArrayResize(tickets,n+1);ArrayResize(ticketLots,n+1);tickets[n]=OrderTicket();ticketLots[n]=OrderLots();}for(int a=0;a<ArraySize(tickets)-1;a++)for(int b=a+1;b<ArraySize(tickets);b++)if(ticketLots[b]>ticketLots[a]){int ti=tickets[a];tickets[a]=tickets[b];tickets[b]=ti;double tl=ticketLots[a];ticketLots[a]=ticketLots[b];ticketLots[b]=tl;}double remaining=NormalizeDouble(lotsToReduce,DigitsLots);bool changed=false;for(int j=0;j<ArraySize(tickets)&&remaining>=Lot;j++){if(!OrderSelect(tickets[j],SELECT_BY_TICKET,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;double available=OrderLots();double closeLots=NormalizeDouble(MathMin(available,remaining),DigitsLots);if(closeLots<Lot)continue;double money=0.0;if(CloseMarketOrderLots(tickets[j],closeLots,money)){remaining=NormalizeDouble(remaining-closeLots,DigitsLots);realizedMoney+=money;changed=true;}}return(changed&&remaining<Lot);}

bool R10FindProfitFundedPair(int direction,int &profitTicket,double &profitLots,double &profitPerLot,int &lossTicket,double &lossLots,double &lossPerLot){profitTicket=-1;lossTicket=-1;profitLots=0.0;lossLots=0.0;profitPerLot=0.0;lossPerLot=0.0;int type=(direction==OP_BUY?OP_BUY:OP_SELL);double bestProfit=-1.0e100,worstLoss=1.0e100;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;double lots=OrderLots();if(lots<Lot)continue;double money=OrderProfit()+OrderSwap()+OrderCommission();double perLot=money/lots;if(money>0.0&&money>bestProfit){bestProfit=money;profitTicket=OrderTicket();profitLots=lots;profitPerLot=perLot;}if(money<0.0&&money<worstLoss){worstLoss=money;lossTicket=OrderTicket();lossLots=lots;lossPerLot=perLot;}}return(profitTicket>0&&lossTicket>0&&profitLots>=Lot&&lossLots>=Lot);}

bool Rule10ProfitFundedPartial(int targetDirection){if(!EnableR10PairReduction||R10PairMinProfit<=0.0)return(false);if(R10PairCooldownSeconds>0&&g_r10LastAction>0&&TimeCurrent()-g_r10LastAction<R10PairCooldownSeconds)return(false);int profitTicket=-1,lossTicket=-1;double profitLots=0.0,lossLots=0.0,profitPerLot=0.0,lossPerLot=0.0;if(!R10FindProfitFundedPair(targetDirection,profitTicket,profitLots,profitPerLot,lossTicket,lossLots,lossPerLot))return(false);double pairLots=NormalizeDouble(MathMin(MathMin(profitLots,lossLots),R10PairMaxLots),DigitsLots);if(pairLots<Lot)return(false);double expectedPairProfit=(profitPerLot+lossPerLot)*pairLots;if(expectedPairProfit<R10PairMinProfit)return(false);double beforeExposure=ExposureLots(),beforeGross=DirectionLots(OP_BUY)+DirectionLots(OP_SELL);double realizedProfit=0.0,realizedLoss=0.0;Print(EA_NAME," RULE 10 PAIR TRIGGER: side=",(targetDirection==OP_BUY?"BUY":"SELL")," profitTicket=",profitTicket," lossTicket=",lossTicket," pairLots=",DoubleToString(pairLots,DigitsLots)," expected=$",DoubleToString(expectedPairProfit,2)," exposure=",DoubleToString(beforeExposure,DigitsLots)," gross=",DoubleToString(beforeGross,DigitsLots));if(!CloseMarketOrderLots(profitTicket,pairLots,realizedProfit))return(false);if(!CloseMarketOrderLots(lossTicket,pairLots,realizedLoss)){Print(EA_NAME," RULE 10 PAIR WARNING: losing-side partial close failed after profitable partial close. Exposure was reduced, but pair was incomplete.");g_r10LastAction=TimeCurrent();return(true);}double afterExposure=ExposureLots(),afterGross=DirectionLots(OP_BUY)+DirectionLots(OP_SELL);double netRealized=realizedProfit+realizedLoss;if(afterExposure>beforeExposure+0.00001){Print(EA_NAME," RULE 10 PAIR SAFETY FAILURE: exposure increased. before=",DoubleToString(beforeExposure,DigitsLots)," after=",DoubleToString(afterExposure,DigitsLots));return(false);}g_r10LastAction=TimeCurrent();Print(EA_NAME," RULE 10 PAIR COMPLETE: side=",(targetDirection==OP_BUY?"BUY":"SELL")," reduced=",DoubleToString(pairLots,DigitsLots)," realized=$",DoubleToString(netRealized,2)," exposure ",DoubleToString(beforeExposure,DigitsLots)," -> ",DoubleToString(afterExposure,DigitsLots)," gross ",DoubleToString(beforeGross,DigitsLots)," -> ",DoubleToString(afterGross,DigitsLots));CreateR10VisualMarker(targetDirection,pairLots,netRealized,beforeExposure,afterExposure,beforeGross,afterGross);CreateEngineActionMarker("R10","REDUCE",targetDirection,pairLots);return(true);}

bool Rule10Reduce(int targetDirection){if(!EnableR10Reduce||R10MinExposureLots<=0.0)return(false);if(Rule10ProfitFundedPartial(targetDirection))return(true);int opposite=(targetDirection==OP_BUY?OP_SELL:OP_BUY);double targetLots=DirectionLots(targetDirection),oppositeLots=DirectionLots(opposite);double exposure=targetLots-oppositeLots;if(exposure<R10MinExposureLots)return(false);if(oppositeLots<Lot)return(false);if(targetLots<=oppositeLots)return(false);double reduceLots=NormalizeDouble(MathMin(exposure,oppositeLots),DigitsLots);if(reduceLots<R10MinExposureLots)return(false);double beforeExposure=ExposureLots(),beforeGross=targetLots+oppositeLots;double targetRealized=0.0,oppositeRealized=0.0;Print(EA_NAME," RULE 10 TRIGGER: target=",(targetDirection==OP_BUY?"BUY":"SELL")," heavy=",DoubleToString(targetLots,DigitsLots)," light=",DoubleToString(oppositeLots,DigitsLots)," exposure=",DoubleToString(beforeExposure,DigitsLots)," gross=",DoubleToString(beforeGross,DigitsLots)," reduce=",DoubleToString(reduceLots,DigitsLots));if(!ReduceDirectionByLots(targetDirection,reduceLots,targetRealized))return(false);if(!ReduceDirectionByLots(opposite,reduceLots,oppositeRealized)){Print(EA_NAME," RULE 10 WARNING: opposite-side reduction failed. System will not add exposure.");return(false);}double afterExposure=ExposureLots(),afterGross=DirectionLots(OP_BUY)+DirectionLots(OP_SELL);if(afterExposure>beforeExposure+0.00001){Print(EA_NAME," RULE 10 SAFETY FAILURE: exposure increased. before=",DoubleToString(beforeExposure,DigitsLots)," after=",DoubleToString(afterExposure,DigitsLots));return(false);}double totalRealized=targetRealized+oppositeRealized;g_r10LastAction=TimeCurrent();Print(EA_NAME," RULE 10 REDUCE COMPLETE: exposure ",DoubleToString(beforeExposure,DigitsLots)," -> ",DoubleToString(afterExposure,DigitsLots)," gross ",DoubleToString(beforeGross,DigitsLots)," -> ",DoubleToString(afterGross,DigitsLots)," realized=$",DoubleToString(totalRealized,2));CreateR10VisualMarker(targetDirection,reduceLots,totalRealized,beforeExposure,afterExposure,beforeGross,afterGross);CreateEngineActionMarker("R10","REDUCE",targetDirection,reduceLots);return(true);}

#endif
