#property strict
#property version   "1.116"
#property description "EAGOLD - BUY/SELL independent machines - Rules 1 to 10 + R10.2 Recovery Realization + Dynamic Recovery Step Multiplier + Persistent Operational State + Isolated R1 Admission Control + R13 Recovery Satellite + R12 M5 Observer + Excursion Telemetry + Counterfactual Path Telemetry + Adaptive Profit Guard + Trading Window + Spread Guard"
#include "../Core/EAGOLD_Config.mqh"
#include "../Core/EAGOLD_ActionContract.mqh"
#include "../Core/EAGOLD_Orders.mqh"
bool IsR13Order();
bool IsR13OwnershipConfigurationValid();
bool EAGOLDValidateOwnershipConfiguration();
#include "../Core/EAGOLD_TradingGuards.mqh"
#include "../Core/EAGOLD_Execution.mqh"
string EA_NAME="EAGOLD";string R10_MARKER_PREFIX="EAGOLD_R10_MARKER_";string ENGINE_MARKER_PREFIX="EAGOLD_ENGINE_";string STATE_PREFIX="EAGOLD_STATE_";bool g_r9HedgeActive=false;bool g_r10V2PreExecutionGate=false;bool g_r10V2PreLiveGate=false;EAGOLD_R10V2PreLiveReason g_r10V2PreLiveReason=EAGOLD_R10V2_PRELIVE_FEATURE_DISABLED;EAGOLD_R10V2ValidationReason g_r10V2PreExecutionReason=EAGOLD_R10V2_VALIDATION_NO_OPPORTUNITY;int g_r9ProcessedTickets[];datetime g_r10LastAction=0;bool g_r10RecoveryCycleActive=false;double g_r10RecoveryStartEquity=0.0;double g_r10RecoveryWorstEquity=0.0;EAGOLD_TickPolicy g_eagoldTickPolicy=EAGOLD_TICK_CONTINUE;
#include "../Engines/EAGOLD_R10_Reconciliation.mqh"
#include "../Engines/EAGOLD_Engine1_LifecycleRecovery_v0116.mqh"
#include "../Engines/EAGOLD_Engine2_Exposure_v0116.mqh"
#include "../Core/EAGOLD_R1_AtomicAdmission.mqh"
#include "../Core/EAGOLD_R7_KeepAlive.mqh"
double PointsToPrice(double points){return(points*Point);}double NormalizePrice(double price){return(NormalizeDouble(price,Digits));}double NormalizeLot(double lot){if(lot<Lot)lot=Lot;if(MaxOpenLot>0.0&&lot>MaxOpenLot)lot=MaxOpenLot;return(NormalizeDouble(lot,DigitsLots));}
void EAGOLD_ResetTickTransaction(){g_eagoldTickPolicy=EAGOLD_TICK_CONTINUE;}
bool EAGOLD_EconomicExecutionAllowed(){return(g_eagoldTickPolicy==EAGOLD_TICK_CONTINUE);}
void EAGOLD_ApplyActionResult(EAGOLD_ActionResult result,string engine,string action,int direction,double lots){EAGOLD_TickPolicy policy=EAGOLD_PolicyForResult(result);Print(EA_NAME," ACTION CONTRACT engine=",engine," action=",action," result=",EAGOLD_ActionResultName(result)," policy=",EAGOLD_TickPolicyName(policy)," direction=",(direction==OP_BUY?"BUY":"SELL")," lots=",DoubleToString(lots,DigitsLots));if(result==EAGOLD_ACTION_PARTIAL)EAGOLD_R10RequestReconciliation();if(policy==EAGOLD_TICK_HALT_FOR_RECONCILIATION)g_eagoldTickPolicy=EAGOLD_TICK_HALT_FOR_RECONCILIATION;else if(policy==EAGOLD_TICK_CONSUME&&g_eagoldTickPolicy==EAGOLD_TICK_CONTINUE)g_eagoldTickPolicy=EAGOLD_TICK_CONSUME;}
#include "../UI/EAGOLD_RealizationCascade.mqh"
#include "../Engines/EAGOLD_R13_Satellite.mqh"
#include "../Core/EAGOLD_Persistence.mqh"
#include "../UI/EAGOLD_ModularizationPanel.mqh"
#include "../UI/EAGOLD_ChartBasketGuides.mqh"
R13ObserverState g_r13Observer;
double EngineMarkerPipsToPrice(double pips){double pipSize=Point;if(Digits==3||Digits==5)pipSize=Point*10.0;return(pips*pipSize);}int EngineMarkerStackLevel(string engine){if(engine=="R1")return(0);if(engine=="R1.1")return(1);if(engine=="R4")return(2);if(engine=="R5"||engine=="BRX")return(3);if(engine=="R7")return(4);if(engine=="R10")return(5);if(engine=="R13")return(6);return(7);}string ResolveEngineMarkerFont(){return("Arial");}
void CreateEngineActionMarker(string engine,string action,int direction,double lots){if(!EnableEngineActionMarkers||Bars<1)return;RefreshRates();datetime stamp=Time[0];double price=NormalizePrice(direction==OP_BUY?Low[0]:High[0]);color markerColor=CascadeEngineColor(engine);string name=ENGINE_MARKER_PREFIX+IntegerToString((int)stamp)+"_"+IntegerToString(GetTickCount())+"_"+IntegerToString(MathRand());if(ObjectCreate(0,name,OBJ_ARROW,0,stamp,price)){ObjectSetInteger(0,name,OBJPROP_ARROWCODE,159);ObjectSetInteger(0,name,OBJPROP_WIDTH,2);ObjectSetInteger(0,name,OBJPROP_COLOR,markerColor);ObjectSetInteger(0,name,OBJPROP_SELECTABLE,false);ObjectSetInteger(0,name,OBJPROP_SELECTED,false);ObjectSetInteger(0,name,OBJPROP_HIDDEN,true);ObjectSetInteger(0,name,OBJPROP_BACK,false);ObjectSetInteger(0,name,OBJPROP_ZORDER,5);}EAGOLD_ActionCascadeAdd(engine);ChartRedraw(0);}
int OnInit()
{
ObjectsDeleteAll(0,ENGINE_MARKER_PREFIX);ObjectsDeleteAll(0,R10_MARKER_PREFIX);ArrayResize(g_r9ProcessedTickets,0);g_r9HedgeActive=false;g_r10LastAction=0;g_r10RecoveryCycleActive=false;g_r10RecoveryStartEquity=0.0;g_r10RecoveryWorstEquity=0.0;g_eagoldTickPolicy=EAGOLD_TICK_CONTINUE;if(!EAGOLDValidateOwnershipConfiguration()||!IsR13OwnershipConfigurationValid()){Print(EA_NAME," INIT BLOCKED: unsafe order ownership configuration. EAGOLD will not trade this chart.");return(INIT_FAILED);}if(EAGOLD_PersistenceEnabled())LoadPersistedStrategicState();else{g_modPanelMinProfit=0.0;g_modPanelMaxLots=0.0;g_modPanelInitialized=true;g_panelMinProfit=0.0;g_panelMaxLots=0.0;g_panelInitialized=true;}R13ResetObserverState(g_r13Observer);R9SeedExistingPositions();R10RecoveryUpdateState();R13Observe(g_r13Observer);EAGOLD_ModPanelUpdate();EAGOLD_RealizationCascadeUpdate();EAGOLD_ChartBasketGuidesUpdate();PersistAllState(true);EAGOLD_CreateFirstOrdersAtomic();R10RecoveryUpdateState();R13Observe(g_r13Observer);EAGOLD_ModPanelUpdate();EAGOLD_RealizationCascadeUpdate();EAGOLD_ChartBasketGuidesUpdate();PersistAllState(true);return(INIT_SUCCEEDED);}
void OnDeinit(const int reason){if(EAGOLD_PersistenceEnabled())PersistAllState(true);EAGOLD_RealizationCascadeDelete();EAGOLD_ChartBasketGuidesDelete();EAGOLD_ModPanelDelete();}
void OnTick(){EAGOLD_ResetTickTransaction();EAGOLD_SuspendInvalidPendingEntries();bool reconciliationRequiredBefore=EAGOLD_R10ReconciliationRequired();bool reconciliationOk=EAGOLD_R10ReconcileIfRequired();if(!reconciliationOk){g_eagoldTickPolicy=EAGOLD_TICK_HALT_FOR_RECONCILIATION;}else if(reconciliationRequiredBefore){EAGOLD_R10V2ExecutionResetAfterReconciliation();}R10RecoveryUpdateState();
if(EAGOLD_EconomicExecutionAllowed()){EAGOLD_ActionResult r9Result=Rule9DetectActivatedOrdersTransactional();if(r9Result!=EAGOLD_ACTION_BLOCKED)EAGOLD_ApplyActionResult(r9Result,"R9","HEDGE",HeavyDirection(),0.0);}if(EAGOLD_EconomicExecutionAllowed()){EAGOLD_ActionResult r7Result=EAGOLD_R7EnsureMissingDirectionTransactional();if(r7Result!=EAGOLD_ACTION_BLOCKED)EAGOLD_ApplyActionResult(r7Result,"R7","KEEP_ALIVE",HeavyDirection(),Lot);}if(EAGOLD_EconomicExecutionAllowed())BuyMachine();if(EAGOLD_EconomicExecutionAllowed())SellMachine();if(EAGOLD_EconomicExecutionAllowed()){EAGOLD_ActionResult r1Result=EAGOLD_CreateFirstOrdersAtomic();if(r1Result!=EAGOLD_ACTION_BLOCKED)EAGOLD_ApplyActionResult(r1Result,"R1","FIRST_SEED",HeavyDirection(),Lot);}if(EAGOLD_EconomicExecutionAllowed())TrailAllStopOrders();if(EAGOLD_EconomicExecutionAllowed())R13Observe(g_r13Observer);ObjectsDeleteAll(0,R10_MARKER_PREFIX);EAGOLD_ModPanelUpdate();EAGOLD_RealizationCascadeUpdate();EAGOLD_ChartBasketGuidesUpdate();PersistAllState(false);}
